### ISSUE TITLE
Warn developer when CollectionView's _insertBefore fails to find index.

### ISSUE THREAD

**Issue by MeoMix** [marionettejs/backbone.marionette#2011] opened 2014-10-22 02:12 UTC
Hi there,

I'm not sure I fully understand the use cases for this method. So, maybe this suggestions doesn't make sense, but lets take a look at it anyway:

	// If we've already rendered the main collection, append
	// the new child into the correct order if we need to. Otherwise
	// append to the end.
	if (!collectionView._insertBefore(childView, index)) {
		collectionView._insertAfter(childView);
	}

	// Internal method. Check whether we need to insert the view into
	// the correct position.
	_insertBefore: function (childView, index) {
		var currentView;
		var findPosition = this.sort && (index < this.children.length - 1);
		if (findPosition) {
			// Find the view after this one
			currentView = this.children.find(function (view) {
				return view._index === index + 1;
			});
		}

		if (currentView) {
			currentView.$el.before(childView.el);
			return true;
		}

		return false;
	},

The _insertBefore method takes a childView and an index. It attempts to find the next child based on that index. If found, the childView is inserted before that index. If not found, the method returns false. If the method returns false, the childView is inserted at the final position in the list.

I've encountered bugs several times in development which have resulted in _insertBefore failing to find the appropriate index through no fault of Marionette -- simply incorrect code on my end. However, the manifestation of the bug is very confusing because the view still appears... simply in the wrong spot. This leads me to check my model's index in its collection, my comparators, my use of sort, and all of my code right up until the CollectionView's addChild method is called with the given index. The index looks good right up to that point, but I've corrupted Babysitter's indices by calling _incrementIndices and _decrementIndices inappropriately. I end up having to dig deep into Marionette's source to see why my view is appearing in an incorrect spot.

If appending at the end of the list is simply a fail-safe for _insertBefore -- might I suggest issuing a warning when it is occurring? If it is not a fail-safe and is an expected part of the process... why? I would say that the appropriate index should be known before calling _insertBefore.

Thoughts?

**Comment by ahumphreys87** [comment] 2015-02-27 21:45
@MeoMix I realise I'm late to the party here...

`_insertAfter` isn't really a fail safe, it's the alternative to inserting the child into the correct place in the DOM. `_insertBefore` checks whether the view should be inserted before the end of the list and inserts it if needs be, otherwise it appends to the end.

I like the idea of a debug mode in inspector but not sure this case should be a warning. Not finding an index isn't really doing anything wrong, its just that this `view` needs to go on the end of the list and not before any other children.

**Comment by MeoMix** [comment] 2015-03-02 19:05
@ahumphreys87 A few things:

- I don't think that a function named _insertBefore implies that it can fail or should not insert in some scenarios. Perhaps splitting it into two functions (canInsertBefore and insertBefore) would be prudent?

- In what scenarios would I tell an item to try to insert before a certain index, fail to find that index, and then add to the end? I would expect the item to not be inserted if it fails to find the appropriate index to insert before. It's not really a graceful recovery to have it appear at the end, in my opinion.

**Comment by ahumphreys87** [comment] 2015-03-02 19:17
@meomix I agree with your first point, it could be named better and split it out.

However your second point, remember this is a private method used for sorting. If you add a model to a collection it could end up needing to be appended before a particular view. It's quite a common scenario when dealing with 

The function is checking whether the child needs to be added before an existing view, if it does then it inserts it - if not it appends it to the end which is the only other place.

Can I ask what you are using _insertBefore for? It's not really intended to be overridden.

**Comment by MeoMix** [comment] 2015-03-02 19:28
@ahumphreys87 

I have a Behavior which enables incremental rendering of ItemViews inside of a CollectionView. Instead of rendering the entire collection it renders a subset of it in a fashion similar to the functionality added in Marionette 2.4, https://github.com/MeoMix/StreamusChromeExtension/blob/Development/src/js/foreground/view/behavior/slidingRender.js

While implementing this functionality, I encountered and reported another bug: https://github.com/marionettejs/backbone.marionette/issues/2021

The gist of it is:

- Overriding the addChild method is supported by Marionette and is outlined in the documentation.
- Calling sort on the collection causes _renderChildren to be called which calls showCollection
- showCollection increments its index while iterating over the collection even if addChild has prevented the child view from being added.

This can result in Babysitter's internal indicies becoming malformed. However, no errors are thrown. _insertBefore just starts appending to the end. This required a substantial amount of debugging into the internals of Marionette and being able to see that this was happening at a glance would've been incredibly helpful.

**Comment by ahumphreys87** [comment] 2015-03-02 19:40
ah ok, that gives it a bit more context. I guess the main issue here is the fact that addChild doesn't correctly manage the indices.

I do think logging or warnings down to this level would be quite verbose though. If we add it here I'd like to see a solution to logging across the board, maybe inspector is the place for this sort of thing - not sold on bulking out the library.

Thoughts @marionettejs/marionette-core ?

**Comment by ahumphreys87** [comment] 2015-04-10 22:07
@MeoMix does the new filter functionality fix this issue for you? Adding a filter should correctly manage the indices within babysitter. I think this is the main issue you were having?

**Comment by ahumphreys87** [comment] 2015-04-12 22:03
Closing as a `filter` should cater for this use case. @MeoMix feel free to reopen is the problem is still there :smile:

**Closed by ahumphreys87** 2015-04-12 22:03 UTC
Labels: discussion
