### ISSUE TITLE
Switch to using external module library

### ISSUE THREAD

**Issue by samccone** [marionettejs/backbone.marionette#2307] opened 2015-02-08 23:08 UTC
now that this is almost ready
https://github.com/marionettejs/marionette.module

We should think about migrating modules out of the core source code in the 2.x branch, and treat it like an external "included" dependency like babysitter and wreqr.

**Comment by jasonLaster** [comment] 2015-02-09 18:49
:thought_balloon: :+1:

**Comment by devel-pa** [comment] 2015-02-24 20:26
Instead of modules I started using this: https://github.com/jfairbank/marionette.component
Allows me to use really decoupled components, from the app, in conjunction with Radio.

**Comment by thejameskyle** [comment] 2015-02-24 22:35
@devel-pa That's unrelated, this is part of how we're removing modules in Marionette in v3.

**Comment by devel-pa** [comment] 2015-02-25 08:26
@thejameskyle OK, understood.

**Comment by paulfalgout** [comment] 2015-04-10 03:35
Where are we on this?  Modules is out of `next` already.. Will we include this as a dependency for v3 and remove it in v4?  Might take some pressure off of the whatever the start/stop solution is and we can release sooner.  @marionettejs/marionette-core ?

**Comment by jasonLaster** [comment] 2015-08-18 21:58
dupe of #2542

**Closed by jasonLaster** 2015-08-18 21:58 UTC
Labels: minor
