### ISSUE TITLE
Default collection event handlers are not copied on setElement

### ISSUE THREAD

**Issue by pimlottc** [marionettejs/backbone.marionette#1940] opened 2014-09-30 03:49 UTC
If you change a view's element via `setElement`, Backbone handles re-binding your events via `undelegateEvents`/`delegateEvents`.  However, this does not include the "automatic rendering" collection bindings for add/remove/reset.  These should be copied as well.

My particular use case is that I have a table widget handles DOM rendering on its own but I'm still using marionette views to consolidate event handling/behavior for individual cells.

**Comment by paulfalgout** [comment] 2015-02-05 04:43
So I think https://github.com/marionettejs/backbone.marionette/pull/2241 solves this issue.  Backbone's `setElement` calls `undelegateEvents` which previously unbound the entity events.  But moving entity event binding into the constructor alone I believe removes the need to have the events re-bound on `setElement`

**Comment by paulfalgout** [comment] 2015-02-06 05:26
Update:  I was way off.  To my defense I'm still up all night with a newborn.  The events in question here are only the events bound in `_initialEvents` on `CollectionView` and they really have nothing to do with any of the event delegation, which clearly aren't in use in the fiddle example.

**Comment by paulfalgout** [comment] 2015-04-11 05:09
So after looking into this a bit further I am unconvinced that this is a bug.

Essentially what is happening is this:

The DOM is being duplicated and the el is set for the collectionview itself, but the el is _not_ re-set for any of the childViews..  so all of the childViews for the original collection would still have _their_ events/triggers and the duplicated DOM ones would not.

This is important because new children are inserted based on other children.. and those children's el is still located in the original collection.
https://github.com/marionettejs/backbone.marionette/blob/master/src/collection-view.js#L499

So the problem is, if you setElement on a CollectionView, you also have to setElement on the children as well, but this is really not something we could support out of the box as who knows if the new $el has the same children?

I'm closing for now, but if I'm missing something, certainly chime in.

**Closed by paulfalgout** 2015-04-11 05:09 UTC
Labels: bug, major
