### ISSUE TITLE
Stop copying regions onto views’ prototypes

### ISSUE THREAD

**Issue by Haraldson** [marionettejs/backbone.marionette#2466] opened 2015-03-31 10:03 UTC
With the recent additions of methods like `getRegion` and `showChildView`, I don’t really see any big value in the convenience of being able to access a region object writing `this.regionName` over the slightly more verbose though more explicit `this.regions.name`.

An added bonus is that people can stop giving their regions stupid and repetitive names like ‘content**Region**’ and ‘menu**Region**’.

My proposal is no doubt a breaking change, so I’m not expecting this to be considered for the 2.x.x versions, but for 3.0.0.

**Comment by JSteunou** [comment] 2015-03-31 10:06
I also would like to see this in 3.0.0

In exactly the same way @Haraldson do add suffix on region name, we are doing it since Mn beginnings (0.9 if I recall), and I really would like to be able to stop this madness :)

**Comment by jasonLaster** [comment] 2015-03-31 16:27
agreed - I think there's another issue for this as well.

**Comment by rogovdm** [comment] 2015-04-03 08:12
+1

**Comment by jmeas** [comment] 2015-04-03 18:22
Closing as dupe of #966. Although 966 is closed, a whole slew of v3 things are closed in favor of #1796.

**Closed by jmeas** 2015-04-03 18:22 UTC
