### ISSUE TITLE
Too old underscore.js bower dependency

### ISSUE THREAD

**Issue by JustBlackBird** [marionettejs/backbone.marionette#2446] opened 2015-03-23 12:03 UTC
The last version of underscore.js is `1.8.2` but Marionette.js restricts the version with `1.4.4 - 1.6.0`. Is it done intensionally? Can we increase the allowed version of underscore.js?

**Comment by quentindemetz** [comment] 2015-03-27 16:38
Using it with 1.8.2 seems to work for me.

**Comment by jmeas** [comment] 2015-04-03 18:23
Dupe of #2230. The problem is about breaking changes. If 1.8 is not compatible with 1.6, then we cannot update it until v3. Marionette, unlike Underscore, follows semver.

**Comment by paulfalgout** [comment] 2015-04-05 04:35
That said updating to `1.8.3` could be added to the `next` branch for v3 now.

**Comment by jridgewell** [comment] 2015-04-05 04:38
@jmeas, v1.8 should backwards compatible with v1.6 — though, not v1.7, we broke the breaking change.

**Comment by panzerdp** [comment] 2015-04-07 08:00
It would be nice to have the backbone and underscore dependencies for the latest versions.
It is weird, because Marionette is growing so fast in it's own versions, but still working with old dependencies.
:+1: for this change.

**Comment by jasonLaster** [comment] 2015-04-09 23:14
:+1:

**Comment by robwierzbowski** [comment] 2015-05-22 14:57
Thanks for working on this. Subscribed to the PR, looking forward to it.

**Comment by sterpe** [comment] 2015-06-04 18:40
I'm  guessing this is related...
```
11:34:16 [10109\0] <sterpe@sterpe-pro:~/github.rp-core/tmp> $ ./node_modules/.bin/bower install backbone.marionette
bower backbone.marionette#*     cached git://github.com/marionettejs/backbone.marionette.git#2.4.1
bower backbone.marionette#*   validate 2.4.1 against git://github.com/marionettejs/backbone.marionette.git#*
bower backbone#1.0.0 - 1.1.2    cached git://github.com/jashkenas/backbone.git#1.1.2
bower backbone#1.0.0 - 1.1.2  validate 1.1.2 against git://github.com/jashkenas/backbone.git#1.0.0 - 1.1.2
bower underscore#1.4.4 - 1.6.0  cached git://github.com/jashkenas/underscore.git#1.6.0
bower underscore#1.4.4 - 1.6.0         validate 1.6.0 against git://github.com/jashkenas/underscore.git#1.4.4 - 1.6.0
bower backbone.babysitter#^0.1.0         cached git://github.com/marionettejs/backbone.babysitter.git#0.1.7
bower backbone.babysitter#^0.1.0       validate 0.1.7 against git://github.com/marionettejs/backbone.babysitter.git#^0.1.0
bower backbone.wreqr#^1.0.0              cached git://github.com/marionettejs/backbone.wreqr.git#1.3.2
bower backbone.wreqr#^1.0.0            validate 1.3.2 against git://github.com/marionettejs/backbone.wreqr.git#^1.0.0
bower jquery#^1.8.0 || ^2.0.0            cached git://github.com/jquery/jquery.git#2.1.4
bower jquery#^1.8.0 || ^2.0.0          validate 2.1.4 against git://github.com/jquery/jquery.git#^1.8.0 || ^2.0.0
bower backbone#>=0.9.9 <=1.2.0           cached git://github.com/jashkenas/backbone.git#1.2.0
bower backbone#>=0.9.9 <=1.2.0         validate 1.2.0 against git://github.com/jashkenas/backbone.git#>=0.9.9 <=1.2.0
bower underscore#>=1.4.0 <=1.8.3         cached git://github.com/jashkenas/underscore.git#1.8.3
bower underscore#>=1.4.0 <=1.8.3       validate 1.8.3 against git://github.com/jashkenas/underscore.git#>=1.4.0 <=1.8.3
bower underscore#>=1.3.3 <=1.7.0         cached git://github.com/jashkenas/underscore.git#1.7.0
bower underscore#>=1.3.3 <=1.7.0       validate 1.7.0 against git://github.com/jashkenas/underscore.git#>=1.3.3 <=1.7.0

Unable to find a suitable version for underscore, please choose one:
    1) underscore#1.4.4 - 1.6.0 which resolved to 1.6.0 and is required by backbone.marionette#2.4.1
    2) underscore#>=1.3.3 <=1.7.0 which resolved to 1.7.0 and is required by backbone.wreqr#1.3.2
    3) underscore#>=1.4.0 <=1.8.3 which resolved to 1.8.3 and is required by backbone.babysitter#0.1.7
    4) underscore#>=1.7.0 which resolved to 1.8.3 and is required by backbone#1.2.0
    5) underscore#>=1.5.0 which resolved to 1.8.3 and is required by backbone#1.1.2

Prefix the choice with ! to persist it to bower.json

? Answer: 
```

Still, how should one resolved this?

**Comment by JustBlackBird** [comment] 2015-06-04 18:48
@sterpe you can try 1.8.3. It seems that it works just fine for the most of use cases (actually I did not face any problems).

**Comment by sterpe** [comment] 2015-06-04 23:48
Thanks.

**Comment by just-boris** [comment] 2015-06-15 07:23
Now we have the following dependency tree:
* marionette v2.4.1 depends from backbone.babysitter v0.1.7 which depends from backbone 1.2.0 which requires underscore >=1.7.0
* marionette itself wants undesrcore <= 1.6.0

So, that means that dependency hell is guaranteed for everyone who installs marionette on blank project.

**Comment by jmeas** [comment] 2015-06-15 14:09
We should just release Marionette v3 *now*, which is whatever is on Master + upgrading Backbone dep. It's silly to wait months and months and months before getting up to speed with Backbone. It should happen immediately.

Also, v2 was released a year ago.

The other remaining changes for v3 can go into v4, which does not need to come a year from now.

//cc @marionettejs/marionette-core

**Comment by ahumphreys87** [comment] 2015-06-15 14:12
@jmeas we are bumping backbone in 2.4.2.

It's non breaking for us, we have bumped underscore as well to 1.8.3 I
think - not sure what is latest :/

**Comment by jmeas** [comment] 2015-06-15 14:17
> @jmeas we are bumping backbone in 2.4.2.

ah, okay ignore me then lol :runner: 

When is that gonna be released? Even that PR has been open for monthz

**Comment by ahumphreys87** [comment] 2015-06-15 14:21
I know :(

It needs some changes as there is some stuff that shouldn't go to 2.4.2, we
just want collectionview fix and bb bump.

@samccone if I make these changes can you publish today?

**Comment by ahumphreys87** [comment] 2015-06-16 23:16
2.4.2 is awaiting release, this fixes these problems.

**Closed by ahumphreys87** 2015-06-16 23:16 UTC

**Comment by samccone** [comment] 2015-06-17 01:32
:+1:
