### ISSUE TITLE
Inherit Behaviors

### ISSUE THREAD

**Issue by fabien** [marionettejs/backbone.marionette#2837] opened 2015-11-30 10:40 UTC
I'm well aware of #2216 but for now, an easy fix would be:

```
Marionette.Behaviors.parseBehaviors = function(view, behaviors, nested) {
  var parentClass = view.constructor.__super__;
  if (parentClass && !nested) {
    behaviors = _.extend({}, _.result(parentClass, 'behaviors'), behaviors);
  }
  return _.chain(behaviors).map(function(options, key) {
    var BehaviorClass = Marionette.Behaviors.getBehaviorClass(options, key);
    
    var behavior = new BehaviorClass(options, view);
    var nestedBehaviors = Marionette.Behaviors.parseBehaviors(view, _.result(behavior, 'behaviors'), true);
    
    return [behavior].concat(nestedBehaviors);
  }).flatten().value();
};
```

Would a PR be welcome?

**Comment by fabien** [comment] 2015-11-30 10:42
Obviously, this is still not full recursive, and therefor limited in depth.

**Comment by fabien** [comment] 2015-11-30 11:17
Here's a new implementation that actually works (to unlimited depth, merging keys from bottom to top-level):

```
var parseBehaviors = function(view, behaviors) {
    return _.chain(behaviors).map(function(options, key) {
        var BehaviorClass = Marionette.Behaviors.getBehaviorClass(options, key);
        
        var behavior = new BehaviorClass(options, view);
        var nestedBehaviors = parseBehaviors(view, _.result(behavior, 'behaviors'));
        
        return [behavior].concat(nestedBehaviors);
    }).flatten().value();
};

Marionette.Behaviors.parseBehaviors = function(view, behaviors) {
    var parentClass = view.constructor.__super__;
    var parentBehaviors = {};
    var parentClass = view.constructor.__super__;
    while (parentClass instanceof Marionette.View) {
        _.defaults(parentBehaviors, _.result(parentClass, 'behaviors'));
        parentClass = parentClass.constructor.__super__;
    }
    return parseBehaviors(view, _.extend({}, parentBehaviors, behaviors));
};
```

**Comment by paulfalgout** [comment] 2015-11-30 16:57
I'm not sure about this.  There are many hashes in Backbone and Marionette that you would not expect to inherit if overridden.  I understand the need for behaviors more than others, but the precedent isn't ideal..  Also we probably shouldn't use `__super__` https://github.com/jashkenas/backbone/pull/3539

The interesting part of this solution however is that it can be handled by the parser rather than in the view extend which makes it more intriguing.

Either way I'd suggest as shallow inheritance as possible.  At which point in the edge case where this was needed the view at the bottom of the inheritance can do some sort of:
```js
var MyView = MyBaseView.extend({
  behaviors: function(){
    var baseBehaviors = MyBaseView.prototype.behaviors;
    return _.extend(baseBehaviors, {
      MyBehavior: {}
    });
  }
});
```

**Comment by jasonLaster** [comment] 2015-11-30 18:28
@fabien thanks for the suggestion. I also appreciate your creative solution to a very hairy problem. This reminds me of one of my first [PRs](https://github.com/marionettejs/backbone.marionette/pull/937), which i think i spent a week on. lol

My opinion to something like this is that simpler/consistent is better. So with something like `behaviors`, a) it should work as 90% of people would first expect, b) it should work like other properties `modelEvents`, `events`, ...

**Comment by fabien** [comment] 2015-11-30 21:34
@paulfalgout @jasonLaster for now, I'm happy to use this in my own projects. I agree that there are many hashes that would benefit from proper inheritance. 

But indeed, Behaviors are special in this regard because they actually were developed to overcome the usual limitation of inheritance-based solutions. Yet, the current implementation prevents you from treating them as 'mixins', in a more standalone manner.

If you could do something like this (with a new `behavior` method):

```
var BaseView = Marionette.ItemView.extend({
    
    constructor: function() {
        Marionette.ItemView.prototype.constructor.apply(this, arguments);
        this.behavior('some-behavior', options); // OR
        this.behavior(SomeBehavior, options);
    }
    
});

var SubView = BaseView.extend({
    
    behaviors: {
       ...
    }
    
});

```

It could be resolved more easily and in a clear way. What do you think?

**Comment by paulfalgout** [comment] 2015-11-30 21:42
hmm interesting.  that seem much more reasonable to me..  and I think that is related to https://github.com/marionettejs/backbone.marionette/issues/2386 and https://github.com/marionettejs/backbone.marionette/issues/2538

There's definitely something here around flexibility for how a behavior is added around instantiation.

**Comment by fabien** [comment] 2015-11-30 21:45
Well, looking at those other issues, having `addBehavior` and `removeBehavior` seems the way to go. Any takers? ;-)

**Comment by paulfalgout** [comment] 2015-11-30 21:49
:-) scary really.  Particularly looking at the `ViewMixin` on the next branch.. figuring out a way to pull the various behavior instantiations out of all of the various functions might be necessary..  like when you add a behavior.. you probably don't want to go around an re-init all of the view, but currently the only things that setup a behavior are tied directly to those various init functions.

**Comment by fabien** [comment] 2015-11-30 21:54
Thing is, some Behaviors alter a view in such a way that 'undoing' that would be (nearly) impossible. If we'll ever get such functionality, we should have a `isRemovable` declaration on such behaviors and set it accordingly. 

For now, I'd be happy to have `addBehavor` or something similar.

PS if I gather correctly, `ViewMixin` contains all the logic that transforms a Backbone View into a Marionette one?

**Comment by paulfalgout** [comment] 2015-11-30 22:16
Ah.. well used to be that there was a base view class that ItemView and CollectionView extended from, but you wouldn't use it directly and it just created some difficulties around ordering in the constructors.  So it was changed to a mixin and all marionette views extend directly from `Backbone.View`

**Comment by paulfalgout** [comment] 2015-11-30 22:16
Also "mixin" is a very loose term here :-)

**Comment by jasonLaster** [comment] 2015-12-03 14:18
Go for it @fabian. AddBehavior would be cool. Should be easier now with the behaviors Mixin. You probably could look at parseBehavior and do it in 30 mins. Step 1, write a test, two run gulp test-browser, step 3 write ten lines of code :)

**Comment by rafde** [comment] 2015-12-04 04:02
had to do something similar when extending a class
```
behaviors: function (){
   var parentBehavior = ParentClass.prototype.behaviors;
   
   if (_.isFunction(parentBehavior)){
      parentBehavior = parentBehavior.call(this);
   }

   return _.defaults(
      {
         myBehavior:{
            behaviorClass: MyBehavior
         }
      },
      parentBehavior
   );
},
```
It's limited because it's shallow. and to be more specific when I wanted to add options to a behavior.

**Comment by paulfalgout** [comment] 2016-01-15 17:30
I'm modifying the title the reflect where the conversation has shifted to

**Comment by paulfalgout** [comment] 2016-01-15 17:31
Closing this as the conversation has moved to being a dupe of https://github.com/marionettejs/backbone.marionette/issues/2538

**Closed by paulfalgout** 2016-01-15 17:31 UTC
Labels: discussion
