### ISSUE TITLE
Introduce a "rootEl" property on the application object

### ISSUE THREAD

**Issue by samccone** [marionettejs/backbone.marionette#2326] opened 2015-02-13 16:26 UTC
With the deprecation of the application regionManager on the Application object, we need a way for people to "kick off" their view stack, scoped to an application.

I propose a solution of allowing a users to specify a `roolEl` property on their application. 

```js
var myApp = new Application({
  rootEl: "#my-app"
}); 

myApp.on("start", () =>
   this.rootEl.show(new FooLayout)
)
```

This is something that we can add to minor and allow people to start migrating away from a region manager today, it will also provide a better answer to people when they ask ... what do i do now since region managers were deprecated.

**Comment by jmeas** [comment] 2015-02-13 16:27
Closing as a duplicate of #2279

**Closed by jmeas** 2015-02-13 16:27 UTC
Labels: enhancement

**Comment by samccone** [comment] 2015-02-13 16:29
derp I thought I had written this before

**Comment by jmeas** [comment] 2015-02-13 16:33
:stuck_out_tongue:
