### ISSUE TITLE
Custom Module Class is being used to define all Modules referenced in Module name (Parent.Child.GrandChild...)

### ISSUE THREAD

**Issue by sklobovskaya** [marionettejs/backbone.marionette#2400] opened 2015-03-06 20:20 UTC
I have a Module named 'One.Two.Three', which I define with a custom Module class. The custom Module's `initialize` method is called once for each of the three Module definitions "One", "Two", and "Three", a total of 3 times. It seems like it should only be called once, for the final module definition "Three".

See this fiddle: http://jsfiddle.net/sklobovskaya/xf5ywqxs/

Sorry if this is already a known issue. Thanks for taking a look.

**Comment by jasonLaster** [comment] 2015-03-06 20:59
That surprises me as well... maybe it's creating all three modules.

like if you do app.start('f1.f2.f3'); it'll start all three

**Comment by samccone** [comment] 2015-03-06 21:00
Yeah I know it does start all sub modules using the "dot" as the delimiter... but this does seem unexpected, alas, modules :( :(

**Comment by sklobovskaya** [comment] 2015-03-06 21:45
It's expected that Marionette creates the parent modules One and Two, because they have not been created yet. However, my custom module's definition is being used to initialize all three of them. 

On line 3710:

      // Loop through all the parts of the module definition
      _.each(moduleNames, function(moduleName, i) {
        var parentModule = module;
        module = this._getModule(parentModule, moduleName, app, moduleDefinition); // <-- here

My custom module class definition is passed in for each of the parent modules, therefore each of the parent modules is going to get defined with my custom class.

**Comment by paulfalgout** [comment] 2015-03-09 00:38
I think the solution here is to define the parent modules if you want to avoid this behavior.

It's honestly a little strange by design, but fixing it is breaking, and this is entirely removed in major.

The best place to deal with this issue might be on the shim https://github.com/marionettejs/marionette.module/blob/master/src/module.js#L166

I think this is possible a wontfix

**Comment by sklobovskaya** [comment] 2015-03-09 00:55
When defining a normal Module "A.B.C", parent modules A and B do not have to be manually defined up front. It's unexpected that anything about how parent modules A and B are defined has to change, just because Module C uses a custom class.

I'm not sure I understand what will break if this is fixed. For example, the following change on line 166 seems to fix the issue:

    // Loop through all the parts of the module definition
    _.each(moduleNames, function(moduleName, i) {
        var parentModule = module;
        module = this._getModule(parentModule, moduleName, app, moduleDefinitions[i]); // pass moduleDefinitions[i] instead of moduleDefinition
        this._addModuleDefinition(parentModule, module, moduleDefinitions[i], customArgs);
    }, this);

Rather than passing Module C's definition for all three Modules A, B, and C, pass in the module definition at the respective module's index, which will be undefined for A and B, and the provided moduleDefinition for C.

Let me know if I misunderstand. Thanks again.

**Comment by paulfalgout** [comment] 2015-03-09 01:49
The solution does seem more reasonable than I expected.  I also don't have a strong grasp for the use-case of overriding a module

It's probably a stretch to say this is breaking:
```js
MyApp.module("One.Two", {
  moduleClass: CustomModule
});

MyApp.module("One", {
  moduleClass: CustomModule
});
```
Only `One` would not be the CustomModule, though the definition is useless and misleading as this would not work now or with the fix, correct?:
```js
MyApp.module("One.Two", {
  moduleClass: CustomModule
});

MyApp.module("One", {
  moduleClass: OtherModule
});
```

But arguably, this is a difficult feature to defend as one of the selling features of the module was [splitting one up](https://github.com/marionettejs/backbone.marionette/blob/master/docs/marionette.module.md#splitting-a-module-definition-apart).  

In the world of splitting one up you have to be consistent with your definitions.
```js
MyApp.module("One.Two");

MyApp.module("One.Two", {
  moduleClass: CustomModule
});
```
would not use the custom class.

So maybe this is a bug worth fixing, but the general design is flawed, and it's deprecated.  The module just has too many concerns for it's own good.

But all of the issues are avoided by defining all modules in order.
```js
MyApp.module("One.Two");
MyApp.module("One.Two.Three", {
  moduleClass: CustomModule
});
```

**Comment by sklobovskaya** [comment] 2015-03-09 02:14
That makes sense to me; I appreciate the explanation. It does seem like the custom class approach falls apart conceptually a bit, when combined with the far more ubiquitous module-splitting feature, as you pointed out. My project does not rely much on custom modules; I only ran into this when experimenting and looking around the docs -- so I might just stick to the "vanilla" Module approach for now.

Thanks again!

**Comment by paulfalgout** [comment] 2015-04-10 03:22
Since modules are deprecated now in Mn, if necessary let's reopen this discussion here: https://github.com/marionettejs/marionette.module/issues

**Closed by paulfalgout** 2015-04-10 03:22 UTC
