### ISSUE TITLE
Approach to tweak nested views

### ISSUE THREAD

**Issue by rogovdm** [marionettejs/backbone.marionette#2905] opened 2016-02-28 14:13 UTC
My layouts goes quite deeps with rendering their child view.

I came up with this ways of dealing with it:

- manual handling of passion all options. Seems quite obligating. 
- use of channel, so sub-...-sub view can ask for some options.
- pass a variable with all nested options to a layout and overwrite basic view class so it will pass that variable to it's children.

And other thought on this question? What is your approach?

Maybe there should be something build in a library to handle with this situation? Sure, it's a very common use case.

**Comment by paulfalgout** [comment] 2016-09-18 04:09
`this.showChildView('myRegion', myChildView, this.options);` works for passing the layouts options down to the children..  not 100% sure what the issue is or what would be easier?

**Comment by paulfalgout** [comment] 2016-10-10 13:17
closing for now.. can reopen if need be.

**Closed by paulfalgout** 2016-10-10 13:17 UTC
