### ISSUE TITLE
Removing Modules in favor of subapps

### ISSUE THREAD

**Issue by cmaher** [marionettejs/backbone.marionette#2026] opened 2014-10-26 21:05 UTC
As of v2.2.2, Marionette has two separate classes for managing the lifecycle of the application and it's components: `Marionette.Application` and `Marionette.Module`. This proposal aims to offer a path for replacing Modules with the Application and subapps.

## Relevant issues
* #1321 - Remove modules / Support multiple apps
* #1796 - v3.0.0 plan

## Current State of Application and Module

`Marionette.Application` is used to start the app and its submodules. It additionally provides a global hook to access modules and the global event channel.

`Marionette.Module` provides a means of starting a portion of the application, including submodules. Modules have the option of immediately starting with their parent, and they can also be stopped (something that can't be done to the application). Modules can be created by extending the `Module` class, or by using the module method on the application, which provides access to the App, for global module access, and the rest of Marionette's dependencies.

Much of the existing capabilities of `Marionette.Application` and `Marionette.Module` are of dubious value in the days of AMD/CommonJS/ES6. Providing global access to the world is very hard to maintain and scale, often requiring manual management of file load order and causing problems when trying to find all the places a particular component is used.  Attaching everything to a namespace under a single variable is no longer considered good practice, and it should not be a focus of the framework. Additionally, the fact that there are so many ways of creating modules is confusing.

## Using the Application to manage the full app lifecycle

Historically, it was only possible to have one Application due to the fact that all instances shared the global channel. Now that the channel is configurable on a per-application basis (#1528), it is trivial to support multiple Applications on the same page. This invites scrutiny of the divide between the `Application` and `Module` classes in the area of app lifecycle management.

There is currently discussion to remove `RegionManager` capabilities and event channel properties from the Application in v3. That would leave the Application with only three behaviors:

1. Starting the application (and any attached submodules)
1. Creating modules with `Application#module`
1. Providing a global hook to for attaching things to

I would argue that only the first behavior is useful, and that the third one is downright harmful.

Meanwhile, module behavior will remain largely unmodified and support the following:

1. Starting themselves and any submodules
1. Starting with the parent module or application
1. Stopping themselves and their submodules
1. Attach themselves as a property of the parent module

All of which but the last are useful and good practice. Interestingly enough Modules will do everything useful that Applications do, but in a more straight-forward manner (the code for making Modules start with the Application lives in the Module).

At this point, it no longer makes sense to have two classes managing application lifecycle. I am proposing that we only have one class to manage application lifecycle, the Application, and that Modules should be replaced with subapps attached to an instance of Application. All subapps would also be instances of Application.

## Subapp API

The usage of the Application and subapps would look as follows

```js
var JellyApp = Marionette.Application.extend({});
var PeanutApp = Marionette.Application.extend({});
var ShellApp = Marionette.Application.extend({});

var MyApp = Marionette.Application.extend({
	// can also be a function
	subapps: {
	  jelly: JellyApp,
	  peanut: {
		applicationClass: PeanutApp,
		butter: true,
		startWithParent: false,
		subapps: {
		  shell: new ShellApp()
		}
	  }
	},

	// can also be a function
	subappOptions: {
	  edible: true
	}
});

var app = new MyApp();
var jellyApp = app.getSubapp('jelly');
var peanutApp = app.getSubapp('peanut');
var shellApp = peanutApp.getSubapp('shell');

jellyApp.edible; // true
peanutApp.edible; //true
peanutApp.butter; // true

app.start();
jellyApp.isRunning(); // true
peanutApp.isRunning(); // false
legumeApp.isRunning(); // false

peanutApp.start();
legumeApp.isRunning() // true

app.stop();
jellyApp.isRunning(); // false
peanutApp.isRunning(); // false
legumeApp.isRunning(); // false
```

## Version Plans

* v2.3
  * Deprecate the behavior whereby an Application extends itself with all of it's options at initialize (separate issue coming).
 * Deprecate initializers on Application and Module, assumed from deprecation of Marionette.Callbacks in #1965 (separate issue coming).
* v3.0.0
  * Remove [this awful line](https://github.com/marionettejs/backbone.marionette/blob/minor/src/application.js#L12) of code. It makes life difficult when adhering to semver (see the confusion caused at #1536), and it really isn't an awesome feature.
  * Remove initializers from Application and Module
* v3.x
  * Add support for subapps in Application
  * Add stop to Application
  * Module will extend application, and its only additional behavior will include whatever is necessary to support `Application#module`
  * Deprecate Module and all supporting methods, e.g.`Application#module`
* v4
  * Remove Module and all supporting methods
  * At this point, I certainly hope no one will care enough about the discussed [Marionette.Namespaces](https://github.com/marionettejs/backbone.marionette/issues/1321#issuecomment-46365053) behavior to actually consider supporting it (but it is a possibility).

Not removing modules immediately in v3 might place a bit of a burden on the code, but I think it is very important from the standpoint of not isolating/splitting the Marionette community. Many Marionette tutorials emphasize modules, and large swaths of  production code almost certainly depend on them.

**Comment by glenpike** [comment] 2015-02-10 13:15
We've been working with an Application, which currently only contains the main router, but uses a lot of Modules.  The main pain point for us was trying to use Modules with RequireJS and not having a dependency on the main Application object on which to call "module()" - unit testing Modules in isolation was important to us.
With hindsight, there are possibly other ways around this - having read [Derick's Browserify Article](http://derickbailey.com/2014/06/10/browserify-my-new-choice-for-modules-in-a-browser-backbone-app/) I am partially inclined to agree with him, but we also want lazy-loading and instanciation of Modules in our application.
**My main request / requirement** for Module or SubApplication definition would be enabling a separation of the dependencies and allowing things to be joined at runtime.
For what it's worth, I just wrote a standalone ModuleStore which duplicates Application.module functionality, enabling Modules to declare themselves and attach to this namespace, then the App can set itself as the base for the namespace at runtime: https://github.com/glenpike/marionette-module-example

**Comment by thejameskyle** [comment] 2015-02-10 19:08
You can use a real module loader to do that, that should not be the responsibility of Marionette.

**Comment by glenpike** [comment] 2015-02-11 11:28
We are using an AMD loader - requirejs - to do the loading of our files with Modules defined.  The problem is the fact we have to call Application.module to create our modules. 
We have been using the [Callback function definition](http://marionettejs.com/docs/v2.3.1/marionette.module.html#callback-function-definition) which would normally mean a dependency on Application in our AMD modules (hence the [workaround](https://github.com/glenpike/marionette-module-example)) 
We are now refactoring to use [Module Classes](http://marionettejs.com/docs/v2.3.1/marionette.module.html#module-classes), which means the Application.module could be called with the loaded AMD module, but I'm not sure if this split seems to have a bit of code smell about it - hence the request to separate the dependency on Module/SubApp "creation" away from the application into a utility function / object.

**Comment by samccone** [comment] 2015-02-11 13:20
@glenpike you will want to follow https://github.com/marionettejs/marionette.module

**Comment by glenpike** [comment] 2015-02-11 14:22
Cool, thanks.

**Comment by thejameskyle** [comment] 2015-02-11 17:48
You should be refactoring your app to remove that though.

**Comment by jasonLaster** [comment] 2015-02-11 18:04
hey @glenpike - I think the module class `Module.extend` approach is a nice one. I've found that it'll set you up well going forward as the Router, App, and Module are better coordinated

**Comment by trusktr** [comment] 2015-02-24 20:29
In #2228 I suggested something similar to the declarative subapp structure at the top of this issue, but for LayoutViews. I like the pattern because it could make it really easy to learn an app's structure without having to dig through a ton of files first.

@cmaher But what happens when a subapp defines it's own subapp structure? Would the subapp's subapps object get mixed with the subapps defined by it's parent? Or would the parent's subapps structure get entirely overriden at that point?

**Comment by rafde** [comment] 2016-09-07 05:45
🏠 keeping. Closing since Mn3 removed modules.

**Closed** 2016-09-07 05:46 UTC
Labels: 0 - Backlog, discussion, enhancement, major
