### ISSUE TITLE
Reverse order in collection when items added with 'at' option

### ISSUE THREAD

**Issue by cybernetlab** [marionettejs/backbone.marionette#2578] opened 2015-06-02 08:36 UTC
I think that I find a bug. Suppose you have a collection, associated with CollectionView instance. When you add a bunch of items (not one by one, but via array of models) to collection with 'at' option (to insert items at specified position) supplied, then child views added in reverse order. [Example on jsfiddle](https://jsfiddle.net/e76hak6g/5/). Code:

```javascript
var ChildView = Mn.ItemView.extend({
    tagName: 'li',
    template: function(data) { return data.name; }
});

var ContainerView = Mn.CollectionView.extend({
    tagName: 'ul',
    childView: ChildView
});

var list = new Backbone.Collection([
    new Backbone.Model({name: 'initial view 1'}),
    new Backbone.Model({name: 'initial view 2'}),
    new Backbone.Model({name: 'initial view 3'})
]);

var view = new ContainerView({collection: list});
view.render();
$('body').append(view.$el);

var additions = [
    new Backbone.Model({name: 'addition view 1'}),
    new Backbone.Model({name: 'addition view 2'}),
    new Backbone.Model({name: 'addition view 3'})
];

list.add(additions, {at: 2});
```

The result is:

```
initial view 1
initial view 2
addition view 3
addition view 2
addition view 1
initial view 3
```

But I'm expecting that it would be

```
initial view 1
initial view 2
addition view 1
addition view 2
addition view 3
initial view 3
```

Regards

**Comment by paulfalgout** [comment] 2015-06-02 15:03
Possible dupe of https://github.com/marionettejs/backbone.marionette/issues/2573

**Comment by ianmstew** [comment] 2015-06-27 16:20
#2573 Was closed in favor of this ticket, so let's continue from here.  @cybernetlab mind opening a PR with a fix and supporting test case against `patch`?

@ahumphreys87 I see you added `v2.5` but now that we have `v2.4.3` I think a patch is most appropriate.  Do you agree?

**Comment by cybernetlab** [comment] 2015-06-27 18:57
@ianmstew I think that I can make PR to fix it. What branch should I use?

**Comment by ianmstew** [comment] 2015-06-29 16:55
:smile:

**Comment by ahumphreys87** [comment] 2015-06-29 17:32
out of interest are these also added in reverse order in the collection?

**Comment by jridgewell** [comment] 2015-06-29 17:40
> out of interest are these also added in reverse order in the collection?

Nope. It's because the trigger event doesn't change the `at` option. In v1.2 we added the `index` option which will correctly provide `at + i` for the true index.

**Comment by cybernetlab** [comment] 2015-07-08 09:56
Sorry - I'm busy now. I'll review my PR at Saturday or Sunday.

**Comment by jasonLaster** [comment] 2015-07-29 14:14
DONE
https://github.com/marionettejs/backbone.marionette/commit/9070bad2940564e7a975e4b0310d25768d986fea

**Closed by jasonLaster** 2015-07-29 14:14 UTC
Labels: bug
