### ISSUE TITLE
Question: How to appropriately architect and manage coupling with behaviors?

### ISSUE THREAD

**Issue by MeoMix** [marionettejs/backbone.marionette#2784] opened 2015-10-14 20:46 UTC
Hey all,

Just had a solid 1+ hr discussion with a coworker regarding this. I'm going to leave my response here completely unbiased and not hint which side I preferred.

We've got a bunch of `WidgetView` instances on the page. Some `WidgetView` instances can be editable and others are not editable. As such, we've got a behavior, `EditableWidgetBehavior`, which helps keep the logic for editing a `WidgetView` DRY.

The overall setup looks like this:

	var WidgetView = Marionette.LayoutView.extend({
	  regions: {
		content: '[data-region=content]'
	  },
	  
	  showContent: function(view){
		this.showChildView('content', view);
	  }
	});
	
    /***** EXAMPLE 1 *******/
	var WidgetView1 = WidgetView.extend({
	  behaviors: {
		  editableWidget: {
			behaviorClass: EditableWidgetBehavior1,
			fetchReadOnlyData: this._fetchReadOnlyData,
			getEditView: this._getEditView,
			getNonEditView: this._getNonEditView
		}
	  },
	  
	  _fetchReadOnlyData: _.noop,
	  _getEditView: _.noop,
	  _getNonEditView: _.noop
	});
	
	var EditableWidgetBehavior1 = Marionette.Behavior.extend({
		defaults: {
			fetchReadOnlyData: _.noop,
			getEditView: null,
			getNonEditView: null
		},

		initialize: function() {
			if (!this.options.getEditView) {
				throw new Error('Behavior must be passed function to create edit view');
			}

			if (!this.options.getNonEditView) {
				throw new Error('Behavior must be passed function to create non edit view');
			}

			this.listenTo(this.view.options.model.get('configuration'), 'change:isEditing', this._onChangeIsEditing);
		},

		onRender: function() {
			this._showContent(this.view.model.get('configuration').get('isEditing'));
		},

		_onChangeIsEditing: function (model, isEditing) {
			this._showContent(isEditing);
		},

		_showContent: function(isEditing) {
			if (isEditing) {
				this._showEditView();
			} else {
				this._showNonEditView();
			}
		},

		_showEditView: function () {
			var editView = this.options.getEditView.call(this.view);
			this.view.showContent(editView);
		},

		_showNonEditView: function() {
			var nonEditView = this.options.getNonEditView.call(this.view);
			this.options.fetchReadOnlyData.call(this.view);
			this.view.showContent(nonEditView);
		}
	});
    /***** EXAMPLE 1 *******/
    /***** EXAMPLE 2 *******/
	var WidgetView2 = WidgetView.extend({
	  behaviors: {
		  editableWidget: {
			behaviorClass: EditableWidgetBehavior2
		}
	  },
	  
	  onShowEditView: function(){
		  this.showContent(this._getEditView());
	  },
	  
	  onShowNonEditView: function(){
		  this._fetchReadOnlyData();
		  this.showContent(this._getNonEditView());
	  },
	  
	  _fetchReadOnlyData: _.noop,
	  _getEditView: _.noop,
	  _getNonEditView: _.noop
	});

	var EditableWidgetBehavior2 = Marionette.Behavior.extend({
		initialize: function() {
			this.listenTo(this.view.options.model.get('configuration'), 'change:isEditing', this._onChangeIsEditing);
		},

		onRender: function() {
			this._showContent(this.view.model.get('configuration').get('isEditing'));
		},

		_onChangeIsEditing: function (model, isEditing) {
			this._showContent(isEditing);
		},

		_showContent: function(isEditing) {
			if (isEditing) {
				this.view.triggerMethod('show:editView');
			} else {
				this.view.triggerMethod('show:nonEditView');
			}
		}
	});
    /***** EXAMPLE 2 *******/

I show two different implementations here. One which leverages callbacks and pushes more onto the behavior and one which leverages `triggerMethod` and keeps more logic on the view.

Does anyone have a strong preference for one of these patterns? If so, could you explain?

Thanks.

**Comment by rafde** [comment] 2015-11-15 21:52
This is a rough one. At work, we tried both implementations in the past and both had drawbacks.

The 2nd example that I like a lot more. 
It allows the behavior to do what it needs to do in accordance to it's specific task. It signals to the view that there are actions happening which the view has the option to react to, but not necessary. I like optional configurations.
The thing is, some times doing stuff like this make is hard to figure out where something is doing the `triggerMethod('show:editView'). It makes it difficult for people who are new to Marionette figure out what was the cause of the event. `show:editView`, I want to know what triggered this event. I still get confused by what text I should be searching for to find this out. I hope that, this case, searching for `onShowEditView` is the function name that I should be doing a file text search on. Now if I have to search the reverse, I have to search for `show:edit:view`.... uh oh. I guess and can do a regex text search.

The 1st example requires the view to define functions, even though it might not need to do one or the other, which forces every view that uses this behavior to do more where they may not want to do by having them pass `_.noop`s to the behavior at times. This behavior also has to do more that `triggerMethod` does already, bind context.
```
_showEditView: function () {
  var editView = this.options.getEditView.call(this.view);
  this.view.showContent(editView);
},
```
uh... what happens if I have to pass parameters to `this.options.getEditView`. I guess I gotta update it to
```
this.options.getEditView.call(this.view, someValue)
```
wait... all the views I want to use this behavior with need a `showContent` defined... or need to pass a `showContent`... hrrmm. By does my behavior have to care about what the view has defined? Shouldn't it care about doing it's own stuff and inform the view that is using it that it's doing stuff? 
I am not big into requiring a view to have to pass functions to behaviors.
But, because you have to be explicit about sending these requirements, it does make it easy to find where the behavior is getting these functions from. Just need to do a search for `getEditView` and I'll find what Views are passing functions to the behaviors.... although I will also see the `_.noop` ones as well.

This made me think about how event names being named `show:editView` makes it difficult to reverse lookup because of the `:` and camelCase support where `show:editView` turns into `onShowEditView`. 
I'm OK with adding `on` but `show:editView` to `showEditView` makes it difficult to review lookup.

**Comment by jeffijoe** [comment] 2015-12-04 10:55
I like example 1 better, and is how I do it personally.

You are already inheriting/implementing some sort of base `WidgetView` - it has a contract that defines what a widget must support.

Now, because this is JS, and JS is awesome, your widget host view (at least thats how I do it) can ask the widget view what it supports, simply by checking for method existence based on the contract - e.g. does `showEditView` exist? Yes, it supports editing, or No, it does not support editing.

The 2nd approach - the event-based one - misuses events IMO. You're *asking* for stuff to be done, while events are supposed to be about stuff that has already happend.

Just my 2 cents.

**Comment by paulfalgout** [comment] 2016-10-25 08:26
I prefer to talk to views from behaviors via events, but only if they're events as @jeffijoe mentioned.  Otherwise it'd be better to just `this.view.someFunc()` or setup a radio channel maybe.. but I rarely find a use for that.  Most of the time if I'm creating a behavior that is doing this, really what I want is some sort of state control and a model would work better.  It looks like you already have the model in this example.

I would not abstract this with a behavior.
```js
var WidgetView = Marionette.LayoutView.extend({
  regions: {
    content: '[data-region=content]'
  },  
  initialize: function() {
    this.config = this.model.get('configuration');
    this.listenTo(this.config, 'change:isEditing', this.onChangeIsEditing);
  },
  onChangeIsEditing: function() {
    this.showContent();
  },
  onRender: function() {
    this.showContent();
  },
  showContent: function(){
    var editView = this.getOption('editView');
    var nonEditView = this.getOption('nonEditView');

    if(this.config.get('isEditing')) {
      this.showChildView('content', editView);
      return;
    }

    this._fetchReadOnlyData();
    this.showChildView('content', nonEditView);
  }
});

```

Anyhow this is sufficiently old.  I'm going to close it for now, but we can revisit if necessary.. Though I think the other issue on guides is probably a better place.

**Closed by paulfalgout** 2016-10-25 08:26 UTC
Labels: discussion
