### ISSUE TITLE
Marionette.CollectionView._onCollectionAdd uses `opts.at` improperly.

### ISSUE THREAD

**Issue by DriverEntry** [marionettejs/backbone.marionette#2573] opened 2015-05-29 10:10 UTC
Thits is how `_onCollectionAdd`, handling `Backbone.Collection` `add` event, determines the child view index.
``` 
_onCollectionAdd: function(child, collection, opts) {
      var index;
      if (opts.at !== undefined) {
        index = opts.at;
      } else {
        index = _.indexOf(this._filteredSortedModels(), child);
      }
...
}
```
The problem is adding an array of models in a collection raises `add` event for each model with the same value of `opts.at`. This makes all the child views to be inserted at the same index i.e. in a reverse order if `opts.at` is specified. jsFiddle http://jsfiddle.net/m00ksmjp/10/.

**Comment by ahumphreys87** [comment] 2015-06-16 22:59
Closing as a dupe of #2578

**Closed by ahumphreys87** 2015-06-16 22:59 UTC
