### ISSUE TITLE
Add "currentTarget" boolean property to View's "triggers" convention

### ISSUE THREAD

**Issue by nmschulte** [marionettejs/backbone.marionette#2875] opened 2016-01-12 20:03 UTC
Hi.  I think a useful addition to the non-shorthand form for the `triggers` View convention would be a `currentTarget` property.  This property would default to `false`, which would produce the existing behavior, but when set to `true`, would only produce the existing behavior if the DOM event's `currentTarget` property was the same as its `target` property.

Thus, the `currentTarget` setting allows restricting the 'trigger' (and subsequent 'event' / 'triggerMethod' hooks) to only a direct user-event: no need to add the (e.g.) "`if (event.currentTarget == event.target) { ... }` to an `events` binding"-boilerplate that really produces 'trigger' semantics.  This can be done via convention configuration, leading to more readable, better code.

Maybe adding this semantic breaks a level of encapsulation that I am not aware of, in which case I'd love to know the details.  I don't think this is the case, though, given how I see `preventDefault` and `stopPropagation` working.  This seems to align well with Marionette's goals.

**Comment by JSteunou** [comment] 2016-01-13 09:35
One way to go around this if you're using babel is to add a decorator making this check for you. https://babeljs.io/docs/plugins/transform-decorators/

**Comment by nmschulte** [comment] 2016-01-13 16:27
@JSteunou I am not using Babel, but that is a neat feature, thank you for sharing.

Since this idea was conceived, I've since gone away from the pattern that instigated the need.  I believe I was blurring certain levels of encapsulation (w/ regard to DOM/view vs JavaScript/logic): I was trying to use browser defaults to effect application behavior (using an anchor element (`<a>`) to "navigate" the application; "change application state" in general).

That said, I still imagine this being a useful addition.  I see now that the simple `event.currentTarget == event.target` logic won't quite work, though.

**Comment by paulfalgout** [comment] 2016-01-15 17:25
If I'm wrong here, lets reopen this, but I believe this is a dupe of https://github.com/marionettejs/backbone.marionette/pull/2690#issuecomment-136871570

**Closed by paulfalgout** 2016-01-15 17:25 UTC

**Comment by nmschulte** [comment] 2016-01-15 19:33
@paulfalgout, thanks for linking that issue.  The problem of encapsulation discussed there, where the DOM event shouldn't escape the View, as the View should encapsulate that, is exactly the issue I was worried about when I was writing this.

I believe my proposal accounts for this (encapsulation of DOM events in the View) concern while providing a bit more boilerplate convenience (like 'triggers' does itself for 'events' (DOM events -> BB events)).

Perhaps you can confirm my understanding: the `triggers` config convention is to make "simple" DOM event -> BB event adaptation/transformation easy (avoiding duplicate 'events' -> callbacks -> this.trigger(...) boilerplating), correct?

**Comment by paulfalgout** [comment] 2016-01-15 20:02
@jmeas @jasonLaster this seems to be a reoccurring issue.  Can you guys better speak into the history in regards the context of this particular issue?
