### ISSUE TITLE
backbone.marionette cannot adapt backbone 1.2.1

### ISSUE THREAD

**Issue by KeyHui** [marionettejs/backbone.marionette#2628] opened 2015-06-26 08:04 UTC
Hi All

backbone.marionette 2.4.2 cannot adapt backbone 1.2.1

thank you

**Comment by ianmstew** [comment] 2015-06-27 14:43
Hi @KeyHui, can you write up a failing test case or show some code that no longer works for you?

**Comment by KeyHui** [comment] 2015-06-28 02:02
Hi @ianmstew 

Marionette.LayoutView.extend({
       initialize:function() {
               this.collection = new Backbone.Collection();
               // it can work
               //this.listenTo(this.collection, 'add', this.addFunc);
        },
        collectionEvents: {
            add: 'addFunc'
        },
       addFunc: function() {
           //it cannot work
           console.log('add')
       },
        onShow: function() {
            this.collection.fetch()
        }
})

I found that collectionEvents cannot work, but it can work, if I bind collection in initialize

thank you

**Comment by paulfalgout** [comment] 2015-06-28 05:17
This is a dupe of https://github.com/marionettejs/backbone.marionette/issues/2605

**Closed by paulfalgout** 2015-06-28 05:17 UTC

**Comment by ianmstew** [comment] 2015-06-29 16:46
@KeyHui thanks for clarifying--looks like this is due to a change in Backbone `1.2.1`, but does not directly break Marionette documentation.  For the time being, you can instead assign the collection in your constructor, like so:

```js
constructor: function () {
  this.collection = new Backbone.Collection();
  Marionette.LayoutView.prototype.constructor.apply(this, arguments);
}
```

In the meantime, an upcoming enhancement will have the side effect of permitting models and collections to be assigned within `initialize` while using Backbone `1.2.1`: https://github.com/marionettejs/backbone.marionette/issues/2605#issuecomment-113177356
