### ISSUE TITLE
[2.4.x] Mn.LayoutView._initializeRegions corrupts prototype's regions definition

### ISSUE THREAD

**Issue by ardi-n** [marionettejs/backbone.marionette#3001] opened 2016-05-06 20:55 UTC
The line `_.extend(regions, regionOptions);` is responsible for that.

Consider we have a CollectionView with LayoutViews as children. Now on first render my CollectionView is initialized from ready DOM. I pass `regions` definition with `el` pointing to existing elements as an option to child LayoutViews. 
Later my collection is updated and I rerender the view. My new child LayoutViews initialize regions with definitions corrupted by the previous CollectionView setup. They aren't passed `regions` option and instead take it from the prototype.

`regions = _.extend({}, regions, regionOptions);` should do the trick.

**Comment by paulfalgout** [comment] 2016-05-06 21:22
This is fixed in `v3` https://github.com/marionettejs/backbone.marionette/blob/next/src/mixins/regions.js#L45

I think a current work-around in `v2`, if you need one, is to make `regions` on the prototype a function returning the hash.

**Comment by paulfalgout** [comment] 2016-05-06 21:25
Hmm that said, even in `v3` the initial regions hash is being changed. To that degree this is intended behavior, as the expectation is that regions "reset" on layout render.

**Comment by ardi-n** [comment] 2016-05-07 09:24
I haven't played with `v3` yet. But defining `regions` as a function on LayoutView's prototype indeed helps. So I think we can close the issue?

**Closed** 2016-05-07 18:37 UTC
