### ISSUE TITLE
Broken functionality after upgrading to Backbone 1.2.x

### ISSUE THREAD

**Issue by quentindemetz** [marionettejs/backbone.marionette#2872] opened 2016-01-03 19:26 UTC
I'm not sure this belongs here or on Backbone's issue tracker, I'll start here.

Consider the following view:
```
var View = Backbone.Marionette.ItemView.extend({

  modelEvents: {
    'change': function() {
      alert('changed')
    }
  },

  initialize: function() {
    this.model = new Backbone.Model();
    window.model = this.model;
  }
});

var view = new View();
```

With Backbone 1.1.2, the model's event listeners are correctly set up when the view is instantiated.
With Backbone 1.2.3, it seems like the model's event listeners are set up earlier (before the initialize function is called). `window.model` does not react to `change` events and `window.model._events` shows there are no event listeners for this model.

Is this intended / have I been using views incorrectly / what's going on ?

Thanks

**Comment by paulfalgout** [comment] 2016-01-04 04:21
dupe of https://github.com/marionettejs/backbone.marionette/issues/2771 and https://github.com/marionettejs/backbone.marionette/issues/2605

backbone doesn't follow semver, so unfortunately there's no real solution here for Marionette.  Since Marionette _does_ follow semver, fixing this in a v2.x release would be breaking.  This is fixed in the upcoming v3 which should be rolling a release candidate shortly https://github.com/marionettejs/backbone.marionette/issues/2836

in the meantime you can re-call `delegateEvents` if you're setting the `model` or `collection` in `initialize`, or just don't do that and pass in the models at instantiation.

**Closed by paulfalgout** 2016-01-04 04:21 UTC

**Comment by quentindemetz** [comment] 2016-01-04 07:46
Thanks!
