### ISSUE TITLE
underscore template variables not parsed with dynamic template functions

### ISSUE THREAD

**Issue by RickHolmes** [marionettejs/backbone.marionette#3277] opened 2016-12-09 18:36 UTC
I am attempting to change a region's view with a common view that uses different templates depending on what is needed. However, underscore variables (i.e. `<%= something %>`) are not being parsed and display as written in the template.

This is true using `getTemplate()`, `template: function(){ return _.template(tpl); }` or determining the template in the initialize method. Neither does it work if I pass a compiled template from the parent view and then re-render the child view.

Is this a bug, am I doing something wrong or do I just need to go to different views for the region, each with its own `template: _.template(tpl),` ?

**Comment by paulfalgout** [comment] 2016-12-09 19:25
I don't follow.  I _think_ you want `getTemplate`.. you definitely don't want template to be a function that returns a template.

If possible, please create a small demo that demonstrates the issue.
You can fork https://jsfiddle.net/marionettejs/adhv48ky/ for quick demo setup.  

```js
const MyView = Mn.View.extend({
  getTemplate() {
    if(this.foo) return _.template('<%- bar %>');
    return _.template('<%- baz %>');
  }
});
```

https://jsfiddle.net/2d29hmue/1/

**Comment by RickHolmes** [comment] 2016-12-09 20:49
Of course -- as usual -- I can't seem to make a simple example. I'm going to have to break my application down to the very basics and see if I can get it to fail and do a Fiddle.

I'm using require.js with the text plugin for all my templates. I doubt it, but could this be the problem?

**Comment by paulfalgout** [comment] 2016-12-10 07:27
I don't use require.js, but a likely place to look first.  essentially whatever you require in should pass the following:
```js
var MyTemplate = _.template('Hello <%- foo %>!');
 _.isFunction(MyTemplate); // returns true
// and
MyTemplate({ foo: 'World' }); // returns the rendered template "Hello World!"
```
The second may depend on the templating engine you're using, but it should be true for underscore

**Comment by RickHolmes** [comment] 2016-12-12 17:18
For some reason, that part of the application started "magically" working. (Don't you hate that!) However, the next template to be loaded does not parse its collection. Here's what's going on:

Everything is loaded with require.js, which also starts the application by requiring something with "App.start()" in it.

For the sake of this latest problem, there are three main parts plus a template. (All of this code is wrapped in `define(['dependency1', 'dependency2'], function(Dependency1, Dependency2){});` so there are no globals.)
```
// app.js: doesn't really do all that much, just starts things rolling
App = new Marionette.Application();
App.on('before:start', function() {
	this.dataPromises = dataController.buildDataCollections(), // dataController passed as dependency
});
App.on('start', function() {
	var self = this;
	
	$.when.apply($, self.dataPromises).then(function() {
		self.formContentView = new FormContentView(); // the "master" view
		self.formContentView.render();
	});
}); 
App.start();
```
```
// dataController: handles all data interaction
var DataController = Marionette.Object.extend({
	channelName: 'data',
	buildDataCollections: function() {
		this.statesCollection = new StatesCollection(); // passed as dependency
		
		return [this.statesCollection.fetch()]; // for the promise callback
	},
	radioRequests: {
		'get:states': 'getStates'	
	},
	// the reply functions
	getStates: function() { 
		return this.statesCollection;
	},
});

var dataController = new DataController();
```
````
// StatesSelect view
var StatesSelectView = Backbone.View.extend({
	initialize: function() {
		this.dataChannel = Radio.channel('data');			
		this.collection = this.dataChannel.request('get:states');
	},
	template: _.template(tpl), 
	tagName: 'select',
	attributes: {
		'id': 'hm-notify-state',
		'class': 'pure-input-1',
		'name': 'hm_notify_state'
	}
});
````
the template for above is loaded with the text plugin for require as a dependency:
````
	<option value="">Choose a state</option>
<% _.each(items), function(item) { %> 
	<option value="<%= item.abbr %>"><%= item.fullName %></option>
<% } %>
````
When the app starts, the main view (a form) is loaded. Its template just has a bunch of empty fieldsets. The first section has three possible sets of content attached to a child view and loaded with different templates. No problems here. The second section has content that relates to the above content, also done the same way. One of these sections has a region that the StatesSelectView uses, which is loaded in its parent view's onRender() method.

The app will load all the views (including the one that wasn't loading the collection earlier), but the options do not load in the select. Nor is there any error shown. The data is definitely loaded and everything's in the correct order as shown by "console.log()". The StatesSelectView itself is loaded, as evidenced by the select element's existence, along with its attributes. Just no content. I have previously done this sort of thing with v2, so I know it does/did work.

A flat html version of the entire form is [here: https;//riversideparknyc.org/testing](https;//riversideparknyc.org/testing) and the Marionette version (as of this post) is [here: https://riversideparknyc.org/testing/donation.html](https://riversideparknyc.org/testing/donation.html). To see the select, choose the membership tab, check the "in honor of" checkbox in the Gift Designation fieldset and check the "send a card" checkbox. You'll see the select there, which should have options, but doesn't.

Now, the "interesting" part is that the StatesSelectView will actually attempt to output this.template() in the console. But it will throw an "items is not defined" error. If I change "items" to "this.collection.models" this.template() runs correctly, but still doesn't load the options into the select.

If you need all the files, let me know and I'll zip things up. 

Sorry for wasting your time if it's just a stupid mistake on my part.

**Comment by paulfalgout** [comment] 2016-12-12 18:24
`Marionette.View` will serialize the `collection` to `items` for the template, but in the code above it is a `Backbone.View`

We can continue this, but I'm closing the ticket since the original issue is resolved.

**Closed by paulfalgout** 2016-12-12 18:24 UTC

**Comment by RickHolmes** [comment] 2016-12-12 18:38
Duh. Sorry, I should have walked away. I haven't used a Backbone view by itself for years.

**Comment by paulfalgout** [comment] 2016-12-12 18:41
:-)  No problem.

**Comment by RickHolmes** [comment] 2016-12-14 13:58
A couple things I have noticed, now that I've got that part working:

If a "normal" view has both a model and a collection, the "items" object is undefined. You can however use "this.collection.models". 

I often try to encapsulate things a bit by letting a view get its own data using Backbone.Radio on initiate. This does not work, the model/collection must be passed in the constructor. If not, the data is available before "render" but the template does not use it. And if you try to use getTemplate() (as opposed to setting the template in the "initiate" method), you'll get an template error. Again, I still can get things to work, but just not the way I prefer to deal with the data.

But then I could just be doing things wrong again.

**Comment by paulfalgout** [comment] 2016-12-14 14:08
If `template` works, but `getTemplate` is causing issues, the issue is elsewhere as `getTemplate` does almost nothing by default: https://github.com/marionettejs/backbone.marionette/blob/master/src/view.js#L155

You can override `serializeData` to work however you need to:  Here is the current implementation which acts as you suggest: https://github.com/marionettejs/backbone.marionette/blob/master/src/view.js#L63

setting the model or collection in `initialize` should really not change anything in `v3`.. the only things that happen prior to `initalize` that _might_ affect `model` or `collection` is region and behavior initialization... but that's pretty edge-casey.
