### ISSUE TITLE
Add isDestroyed flag to Mn.Object/Mn.Class

### ISSUE THREAD

**Issue by pascalpp** [marionettejs/backbone.marionette#2620] opened 2015-06-25 15:26 UTC
When an object is destroyed, it should be marked with `isDestroyed = true` in the same way that views are.

Use case: I have an object which calls one of its methods on a 5-second `_.delay` after being instantiated. If the object is destroyed in the mean time, that delayed method needs a way to detect that the object has been destroyed and return early.

Workaround: I've added an `onDestroy` method to my controller and applied the `isDestroyed` flag myself.

(I understand that Marionette.Object is getting replaced by Marionette.Class in a future version; the same issue applies.)

**Comment by pascalpp** [comment] 2015-06-25 15:34
Wondering what to make of the above suggestion in light of https://github.com/marionettejs/backbone.marionette/issues/2170

**Comment by samccone** [comment] 2015-06-25 15:51
I think adding a isDestroyed prop to Marionette.Object is a good idea, it would allow us to lift it from Mn.View

**Comment by paulfalgout** [comment] 2015-06-25 15:56
This is actually kind of a dupe of https://github.com/marionettejs/backbone.marionette/pull/2352 
Though I think I'm in favor of `isDestroyed` working the same everywhere

**Comment by ahumphreys87** [comment] 2015-06-25 22:29
@pascalpp would you be interested in submitting a PR for this work?

**Comment by pascalpp** [comment] 2015-06-25 22:40
Sure. I think? It's only a one-line change. Stay tuned.

**Comment by pascalpp** [comment] 2015-06-25 23:09
Ok it was more like three lines and a couple tests.

**Comment by ahumphreys87** [comment] 2015-06-26 21:17
fixed with #2626

**Closed by ahumphreys87** 2015-06-26 21:17 UTC
Labels: minor
