### ISSUE TITLE
LayoutView.onBeforeShow doesn't work as expected.

### ISSUE THREAD

**Issue by trusktr** [marionettejs/backbone.marionette#2227] opened 2015-01-30 05:32 UTC
I have a Application. That app creates a new LayoutView. The LayoutView has an onBeforeShow method in which views are added to regions of the LayoutView.

In the app, I'm making the top-level view then rendering it.

```js
var view = new LayoutView
view.render()
```

The onBeforeShow method of the LayoutView never gets called, and so none of it's nested views ever appear.

If I change the name of onBeforeShow to onRender, it all works (with the mentioned [performance penalties](http://marionettejs.com/docs/v2.3.1/marionette.layoutview.html#efficient-nested-view-structures)).

Also, regions inside of Application are deprecated, so obviously I'm not going to call region.show(view) inside the application, which I have a feeling will make everything work.

Can this be fixed, considering that regions in Applications have been deprecated?

**Comment by jmeas** [comment] 2015-01-30 05:49
@trusktr, the events are working as intended. `show` and `attach` are a feature of **child** views. They're triggered by Regions and Collection Views on the child view that is being shown. In the case of a top-level view, there is no view that is showing them, so consequently these events aren't triggered, and things are working as expected.

Using `onRender` is fine for the root view. The browsers I looked at will collapse it into a single paint once the callstack has finished executing. If the children still do their thing in `onBeforeShow`, then you shouldn't notice any perf hits. I admit that this does bring to light an ugliness with our nested view situation, and view events in general.

I think what we need right now is a guide on using a root view, and maybe an update to that doc to discuss more nuances with rendering views efficiently.

**Comment by trusktr** [comment] 2015-01-30 05:51
That definitely would be great! Thanks!

**Comment by jmeas** [comment] 2015-01-30 05:52
Awesome! If you don't mind, I'm gonna keep this open to remind myself that we could use that doc update.

**Comment by jasonLaster** [comment] 2015-01-30 15:27
@jmeas mind creating a new issue for the doc change.

**Comment by ianmstew** [comment] 2015-03-19 20:22
It thought I'd note there is a case where onBeforeShow does not fire when a child of a CollectionView.  See #2428.

**Comment by anextro** [comment] 2015-04-20 01:44
@jmeas i've been dealing with this same issue for the past 15mins.
I later used onBeforeRender and it worked fine. Thinking about whether to use onRender would habe been the right choice.
Also i think we need to reach a conclusion/convention on the rootview of choice.(region or layoutview).
In addition, is there somekind of guide on how to do view selection based on the route.
e.g /welcome and /users/34 should have different views even if they might have the same region loading them.
I have seen implementations using the messaging system(radio and wreq) to do this. While i think this is good from the angle of seperation of concerns, do you know of any better way.?
Finally what do you think about the idea of drawing out a view tree gradually as the app is being developed?

Thanks.

**Comment by ianmstew** [comment] 2015-04-21 15:05
@anextro `onRender` is definitely what you want, because anything based on your `el` or template will be initialized, including your view's UI hash.

I do believe a top level LayoutView (attached to `<body>`, per se) is ideal, because a LayoutView comes with a RegionManager and the convenient `regions` hash for easily defining child regions.  This will be reflected in the doc update slated for 3.0.

As for view selection based on route, this shouldn't necessarily affect your root view.  I see the root view as "always attached" in the same way that app regions are.  Here's an alternative to using Radio for showing views into top level regions: https://github.com/thejameskyle/marionette-wires/blob/master/src/main.js.  Also, come chat in more detail with us at https://gitter.im/marionettejs/backbone.marionette

**Comment by anextro** [comment] 2015-04-21 15:34
@ianmstew i totally agree with you that onRender is the way to go though onBeforeRender still gives the same result(maybe luck or bug).

Also i think i can relate to what am seeing here  https://github.com/thejameskyle/marionette-wires/blob/master/src/main.js but its not fully clear.

I will check you up on gitter. Thanks.

**Comment by ianmstew** [comment] 2015-04-21 15:51
:+1: Yes, the marionette-wires app is not a "beginner" app and it is highly opinionated, but it is also forward-thinking.  What you are seeing here is an "app" handing "app regions" to "sub apps" through the "container" parameter.  These subapps also define their own routes, and when a route is triggered, the subapp shows a view into its container.  Spend some time reading through the code, and we can also talk about simpler approaches, too, on gitter.

**Comment by anextro** [comment] 2015-04-21 19:28
I will definitely spend sometime studying it. It's always good to appreciate standard stuff. Thanks @ianmstew

**Comment by ianmstew** [comment] 2015-04-21 19:30
No problem @anextro!

**Comment by paulfalgout** [comment] 2016-02-17 01:53
Closed by https://github.com/marionettejs/backbone.marionette/pull/2850

**Closed by paulfalgout** 2016-02-17 01:53 UTC
Labels: docs

**Comment by DFallas** [comment] 2016-06-29 16:40
Hi guys think this issue is closed, but adding a comment on doc will be highly appreciated thanks.
